# Set permissions for /etc/passwd, /etc/group, /etc/shadow, .bash_history
echo "Securing file permissions..."

chmod 755 /etc/resolvconf/resolv.conf.d/
chmod 644 /etc/resolvconf/resolv.conf.d/base
chmod 777 /etc/resolv.conf
chmod 644 /etc/hosts
chmod 644 /etc/host.conf
chmod 644 /etc/hosts.deny
chmod 755 /etc/apt/
chmod 755 /etc/apt/apt.conf.d/
chmod 644 /etc/apt/apt.conf.d/10periodic
chmod 644 /etc/apt/apt.conf.d/20auto-upgrades
chmod 664 /etc/apt/sources.list
chmod 644 /etc/default/ufw
chmod 755 /etc/ufw/
chmod 644 /etc/ufw/sysctl.conf
chmod 755 /etc/sysctl.d/
chmod 644 /etc/sysctl.conf
chmod 644 /proc/sys/net/ipv4/ip_forward
chmod 644 /etc/passwd
chmod 600 /etc/shadow
chmod 644 /etc/group
chmod 640 /etc/gshadow
chmod 755 /etc/sudoers.d/
chmod 440 /etc/sudoers.d/*
chmod 644 /etc/deluser.conf
chmod 644 /etc/adduser.conf
chmod 644 /etc/login.defs
chmod 644 /etc/pam.d/common-auth
chmod 644 /etc/pam.d/common-password
chmod 755 /etc/rc.local
chmod 755 /etc/grub.d/
chmod 600 /etc/securetty
chmod 644 /etc/security/limits.conf
chmod 664 /etc/fstab
chmod 644 /etc/updatedb.conf
chmod 644 /etc/modprobe.d/blacklist.conf
chmod 644 /etc/environment
chmod 755 /etc
chmod 755 /bin
chmod 755 /boot
chmod 775 /cdrom
chmod 755 /dev
chmod 755 /home
chmod 755 /lib
chmod 755 /media
chmod 755 /mnt
chmod 755 /opt
chmod 555 /proc/
chmod 700 /root
chmod 755 /run
chmod 755 /sbin
chmod 755 /snap
chmod 755 /srv
chmod 555 /sys
chmod 1755 /tmp
chmod 755 /usr
chmod 755 /var/
chown root:root /etc/resolvconf/resolv.conf.d/
chown root:root /etc/resolvconf/resolv.conf.d/base
chown root:root /etc/resolv.conf
chown root:root /etc/hosts
chown root:root /etc/host.conf
chown root:root /etc/hosts.deny
chown root:root /etc/apt/
chown root:root /etc/apt/apt.conf.d/
chown root:root /etc/apt/apt.conf.d/10periodic
chown root:root /etc/apt/apt.conf.d/20auto-upgrades
chown root:root /etc/apt/sources.list
chown root:root /etc/default/ufw
chown root:root /etc/ufw/
chown root:root /etc/ufw/sysctl.conf
chown root:root /etc/sysctl.d/
chown root:root /etc/sysctl.conf
chown root:root /proc/sys/net/ipv4/ip_forward
chown root:root /etc/passwd
chown root:shadow /etc/shadow
chown root:root /etc/group
chown root:shadow /etc/gshadow
chown root:root /etc/sudoers.d/
chown root:root /etc/sudoers.d/*
chown root:root /etc/sudoers
chown root:root /etc/deluser.conf
chown root:root /etc/adduser.conf
chown root:root /etc/lightdm/lightdm.conf
chown root:root /etc/login.defs
chown root:root /etc/pam.d/common-auth
chown root:root /etc/pam.d/common-password
chown root:root /etc/rc.local
chown root:root /etc/grub.d/
chown root:root /etc/securetty
chown root:root /etc/security/limits.conf
chown root:root /etc/fstab
chown root:root /etc/updatedb.conf
chown root:root /etc/modprobe.d/blacklist.conf
chown root:root /etc/environment
chown root:root /etc
chown root:root /bin
chown root:root /boot
chown root:root /cdrom
chown root:root /dev
chown root:root /home
chown root:root /lib
chown root:root /media
chown root:root /mnt
chown root:root /opt
chown root:root /proc/
chown root:root /root
chown root:root /run
chown root:root /sbin
chown root:root /snap
chown root:root /srv
chown root:root /sys
chown root:root /tmp
chown root:root /usr
chown root:root /var/
chown -R root:root /etc/apache2
chmod 600 /etc/shadow
chmod 640 ~/.bash_history
chmod 0755 /bin/bash

# Additional files and directories to secure
chmod 600 /etc/gshadow
chmod 644 /etc/lightdm/lightdm.conf
chmod 644 /etc/gdm3/custom.conf
chmod 644 /etc/hostname
chmod 600 /etc/ssh/ssh_host_*_key
chmod 644 /etc/ssh/ssh_host_*_key.pub

# Secure sudoers file if it exists
if [ -f /etc/sudoers ]; then
    chmod 440 /etc/sudoers
fi

echo "File permissions secured."
